version: '3.5'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: news-aggregator
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    
  playwright:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playwright-tests
    ports:
      - '3333:3333'
    depends_on:
      - app
    command: npx playwright test --ui-port=3333 --ui-host=0.0.0.0
    environment:
      - NODE_ENV=test
    volumes:
      - .:/app
      - /app/node_modules